In [1]:
import pandas as pd

In [2]:
df_0 = pd.read_excel('0_Papers.xlsx')
print(df_0.shape)
df_0.head()

(36038, 56)

,index,Rank,Publication ID,DOI,PMID,PMCID,ISBN,Title,Abstract,Acknowledgements,...,Source Linkout,Dimensions URL,Fields of Research (ANZSRC 2020),RCDC Categories,HRCS HC Categories,HRCS RAC Categories,Cancer Types,CSO Categories,Units of Assessment,Sustainable Development Goals
0,0,18477,pub.1058596245,10.1086/286122,18811324.0,NaN,NaN,Direct and indirect effects of predation and p...,Indirect effects emerge when a change in the a...,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,A05 Biological Sciences,NaN
1,1,12430,pub.1038418731,10.1007/s004420050410,28308037.0,NaN,NaN,Fitness and community consequences of avoiding...,Abstract We investigated the fitness and commu...,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,"A06 Agriculture, Veterinary and Food Science",NaN
2,2,12406,pub.1008775294,10.1007/bf00566967,28313992.0,NaN,NaN,Predictions of species interactions from consu...,We tested the ability of consumer-resource the...,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,"A06 Agriculture, Veterinary and Food Science",NaN
3,3,11323,pub.1034067250,10.1007/s004420050808,28307770.0,NaN,NaN,Additive interactions between the moon snail E...,Abstract A laboratory experiment was conducted...,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,B07 Earth Systems and Environmental Sciences,3 Good Health and Well Being
4,4,10958,pub.1040724891,10.1016/0169-5347(91)90023-q,21232460.0,NaN,NaN,Indirect effects in community ecology: Their d...,The diversity of indirect interactions that ca...,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,A05 Biological Sciences,NaN

In [3]:
df_1 = pd.read_csv('1_Papers_Cleaned.csv')
print(df_1.shape)
df_1.head()

(33020, 55)

C:\Users\lbeln\AppData\Local\Temp\ipykernel_19796\304606920.py:1: DtypeWarning: Columns (4,15,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df_1 = pd.read_csv('1_Papers_Cleaned.csv')

,Rank,Publication ID,DOI,PMID,PMCID,ISBN,Title,Abstract,Acknowledgements,Funding,...,Source Linkout,Dimensions URL,Fields of Research (ANZSRC 2020),RCDC Categories,HRCS HC Categories,HRCS RAC Categories,Cancer Types,CSO Categories,Units of Assessment,Sustainable Development Goals
0,18477,pub.1058596245,10.1086/286122,18811324.0,NaN,NaN,Direct and indirect effects of predation and p...,Indirect effects emerge when a change in the a...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,A05 Biological Sciences,NaN
1,12430,pub.1038418731,10.1007/s004420050410,28308037.0,NaN,NaN,Fitness and community consequences of avoiding...,Abstract We investigated the fitness and commu...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,"A06 Agriculture, Veterinary and Food Science",NaN
2,12406,pub.1008775294,10.1007/bf00566967,28313992.0,NaN,NaN,Predictions of species interactions from consu...,We tested the ability of consumer-resource the...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,"A06 Agriculture, Veterinary and Food Science",NaN
3,11323,pub.1034067250,10.1007/s004420050808,28307770.0,NaN,NaN,Additive interactions between the moon snail E...,Abstract A laboratory experiment was conducted...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,B07 Earth Systems and Environmental Sciences,3 Good Health and Well Being
4,10958,pub.1040724891,10.1016/0169-5347(91)90023-q,21232460.0,NaN,NaN,Indirect effects in community ecology: Their d...,The diversity of indirect interactions that ca...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,A05 Biological Sciences,NaN

In [4]:
df_2 = pd.read_csv('2_Papers_Screened.csv')
print(df_2.shape)
df_2.head()

(32754, 55)

,Rank,Publication ID,DOI,PMID,PMCID,ISBN,Title,Abstract,Acknowledgements,Funding,...,Source Linkout,Dimensions URL,Fields of Research (ANZSRC 2020),RCDC Categories,HRCS HC Categories,HRCS RAC Categories,Cancer Types,CSO Categories,Units of Assessment,Sustainable Development Goals
0,18477,pub.1058596245,10.1086/286122,18811324.0,NaN,NaN,Direct and indirect effects of predation and p...,Indirect effects emerge when a change in the a...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,A05 Biological Sciences,NaN
1,12430,pub.1038418731,10.1007/s004420050410,28308037.0,NaN,NaN,Fitness and community consequences of avoiding...,Abstract We investigated the fitness and commu...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,"A06 Agriculture, Veterinary and Food Science",NaN
2,12406,pub.1008775294,10.1007/bf00566967,28313992.0,NaN,NaN,Predictions of species interactions from consu...,We tested the ability of consumer-resource the...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,"A06 Agriculture, Veterinary and Food Science",NaN
3,11323,pub.1034067250,10.1007/s004420050808,28307770.0,NaN,NaN,Additive interactions between the moon snail E...,Abstract A laboratory experiment was conducted...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,B07 Earth Systems and Environmental Sciences,3 Good Health and Well Being
4,10958,pub.1040724891,10.1016/0169-5347(91)90023-q,21232460.0,NaN,NaN,Indirect effects in community ecology: Their d...,The diversity of indirect interactions that ca...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,A05 Biological Sciences,NaN

In [5]:
df_3 = pd.read_csv('3_Papers_Screened.csv')
print(df_3.shape)
df_3.head()

(27783, 55)

,Rank,Publication ID,DOI,PMID,PMCID,ISBN,Title,Abstract,Acknowledgements,Funding,...,Source Linkout,Dimensions URL,Fields of Research (ANZSRC 2020),RCDC Categories,HRCS HC Categories,HRCS RAC Categories,Cancer Types,CSO Categories,Units of Assessment,Sustainable Development Goals
0,18477,pub.1058596245,10.1086/286122,18811324.0,NaN,NaN,Direct and indirect effects of predation and p...,Indirect effects emerge when a change in the a...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,A05 Biological Sciences,NaN
1,12430,pub.1038418731,10.1007/s004420050410,28308037.0,NaN,NaN,Fitness and community consequences of avoiding...,Abstract We investigated the fitness and commu...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,"A06 Agriculture, Veterinary and Food Science",NaN
2,12406,pub.1008775294,10.1007/bf00566967,28313992.0,NaN,NaN,Predictions of species interactions from consu...,We tested the ability of consumer-resource the...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,"A06 Agriculture, Veterinary and Food Science",NaN
3,11323,pub.1034067250,10.1007/s004420050808,28307770.0,NaN,NaN,Additive interactions between the moon snail E...,Abstract A laboratory experiment was conducted...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,B07 Earth Systems and Environmental Sciences,3 Good Health and Well Being
4,10958,pub.1040724891,10.1016/0169-5347(91)90023-q,21232460.0,NaN,NaN,Indirect effects in community ecology: Their d...,The diversity of indirect interactions that ca...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,A05 Biological Sciences,NaN

In [6]:
import pickle

In [7]:
with open('4-ScreenByEntities-0.pickle', 'rb') as file:
    mask = pickle.load(file)
print(f'Keys: {mask.keys()}')
print(f'Mask Length: {len(mask["mask"])}')

Keys: dict_keys(['counts', 'mask', 'errors'])
Mask Length: 27783

In [8]:
df_4 = df_3[mask['mask']]
print(df_4.shape)
df_4.head()

(20578, 55)

,Rank,Publication ID,DOI,PMID,PMCID,ISBN,Title,Abstract,Acknowledgements,Funding,...,Source Linkout,Dimensions URL,Fields of Research (ANZSRC 2020),RCDC Categories,HRCS HC Categories,HRCS RAC Categories,Cancer Types,CSO Categories,Units of Assessment,Sustainable Development Goals
0,18477,pub.1058596245,10.1086/286122,18811324.0,NaN,NaN,Direct and indirect effects of predation and p...,Indirect effects emerge when a change in the a...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,A05 Biological Sciences,NaN
1,12430,pub.1038418731,10.1007/s004420050410,28308037.0,NaN,NaN,Fitness and community consequences of avoiding...,Abstract We investigated the fitness and commu...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,"A06 Agriculture, Veterinary and Food Science",NaN
2,12406,pub.1008775294,10.1007/bf00566967,28313992.0,NaN,NaN,Predictions of species interactions from consu...,We tested the ability of consumer-resource the...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,"A06 Agriculture, Veterinary and Food Science",NaN
3,11323,pub.1034067250,10.1007/s004420050808,28307770.0,NaN,NaN,Additive interactions between the moon snail E...,Abstract A laboratory experiment was conducted...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology,NaN,NaN,NaN,NaN,NaN,B07 Earth Systems and Environmental Sciences,3 Good Health and Well Being
5,10585,pub.1039348264,10.1007/bf00323765,28312500.0,NaN,NaN,Experimental studies on direct and indirect in...,We used a complete block design to experimenta...,NaN,NaN,...,NaN,https://app.dimensions.ai/details/publication/...,31 Biological Sciences; 3103 Ecology; 3104 Evo...,NaN,NaN,NaN,NaN,NaN,A05 Biological Sciences,NaN

In [9]:
df_1_dimensions_urls = df_1['Dimensions URL'].tolist()
df_2_dimensions_urls = df_2['Dimensions URL'].tolist()
df_3_dimensions_urls = df_3['Dimensions URL'].tolist()
df_4_dimensions_urls = df_4['Dimensions URL'].tolist()

In [10]:
df_0_filtered = df_0[~df_0['Dimensions URL'].isin(df_1_dimensions_urls)]
print(df_0_filtered.shape)
assert df_0_filtered.shape[0] == df_0.shape[0] - df_1.shape[0]

df_0_filtered_sample = df_0_filtered.sample(n=20)
df_0_filtered_sample.to_csv('0_Papers_Cleaned_And_Excluded_By_Topic_Sample.csv', index=False)

(3018, 56)

In [11]:
df_1_filtered = df_1[~df_1['Dimensions URL'].isin(df_2_dimensions_urls)]
print(df_1_filtered.shape)
assert df_1_filtered.shape[0] == df_1.shape[0] - df_2.shape[0]

df_1_filtered_sample = df_1_filtered.sample(n=20)
df_1_filtered_sample.to_csv('1_Papers_Excluded_By_Language_Sample.csv', index=False)

(266, 55)

In [12]:
df_2_filtered = df_2[~df_2['Dimensions URL'].isin(df_3_dimensions_urls)]
print(df_2_filtered.shape)
assert df_2_filtered.shape[0] == df_2.shape[0] - df_3.shape[0]

df_2_filtered_sample = df_2_filtered.sample(n=20)
df_2_filtered_sample.to_csv('2_Papers_Excluded_By_Keyword_Sample.csv', index=False)

(4971, 55)

In [13]:
df_3_filtered = df_3[~df_3['Dimensions URL'].isin(df_4_dimensions_urls)]
print(df_3_filtered.shape)
assert df_3_filtered.shape[0] == df_3.shape[0] - df_4.shape[0]

df_3_filtered_sample = df_3_filtered.sample(n=20)
df_3_filtered_sample.to_csv('3_Papers_Excluded_By_Entity_Sample.csv', index=False)

(7205, 55)